# title: Object Oriented System Design
# description: Easy to understand notes for every topic
# author:
#   name: Faisal
#   email: m.faisal.s@outlook.com
# minima:
#   skin: dark
#   social_links:
#     - { platform: devto,          user_url: "https://dev.to/jekyll" }
#     - { platform: dribbble,       user_url: "https://dribbble.com/jekyll" }
#     - { platform: facebook,       user_url: "https://www.facebook.com/jekyll" }
#     - { platform: flickr,         user_url: "https://www.flickr.com/photos/jekyll" }
#     - { platform: github,         user_url: "https://github.com/jekyll/minima" }
#     - { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=qc6CJjYAAAAJ" }
#     - { platform: instagram,      user_url: "https://www.instagram.com/faisalsaifii" }
#     - { platform: keybase,        user_url: "https://keybase.io/jekyll" }
#     - { platform: linkedin,       user_url: "https://www.linkedin.com/in/jekyll" }
#     - { platform: microdotblog,   user_url: "https://micro.blog/jekyll" }
#     - { platform: pinterest,      user_url: "https://www.pinterest.com/jekyll" }
#     - { platform: stackoverflow,  user_url: "https://stackoverflow.com/users/1234567/jekyll" }
#     - { platform: telegram,       user_url: "https://t.me/jekyll" }
#     - { platform: twitter,        user_url: "https://twitter.com/jekyllrb" }
#     - { platform: youtube,        user_url: "https://www.youtube.com/@faisalsaifi" }
# theme: minima
# plugins:
#  - jekyll-feed
#  - jekyll-seo-tag